@startuml
'https://plantuml.com/class-diagram

!theme mono

class main {
    + int main()
}

class Engine {
    - Renderer m_renderer
    - GameData m_gameData
    - EventHandler m_eventHandler
    - bool m_running = true

    + Engine()
    + ~Engine()
    + void run()
    - void readInput()
    - void update()
    - void render()
}

class EventHandler {
    - queue<pair<SDL_Event, SDL_EventType>> m_eventQueue

    + void enqueueEvent(SDL_Event &event, SDL_EventType eventType)
    + void processEvents(GameData &gameData)
}

class Renderer {
    - SDL_Window *m_window
    - SDL_Renderer *m_renderer

    + Renderer()
    + ~Renderer()
    + void clear()
    + void present()
}

struct GameData {
    + Map m_map
    + vector<Entity> m_entities

    + void renderMap(Renderer &ren)
    + void renderEntities(Renderer &ren)
}

struct Map {
    + vector<vector<Tile>> m_tiles

    + void renderTiles(Renderer &ren)
}

struct Tile {
    + SDL_Texture m_texture
    + SDL_Rect m_posRect

    + void renderSelf(Renderer &ren)
}

class Entity {
    + void renderSelf(Renderer &ren)
}





main <-- Engine : calls constructor

Engine *-- Renderer
Engine *-- GameData
Engine *-- EventHandler

GameData *-- Map
GameData *-- Entity

Map *-- Tile

@enduml